name: repair_shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  collection: ^1.18.0
  cupertino_icons: 1.0.2
  easy_stepper: 0.8.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_typeahead: ^5.2.0
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  table_calendar: ^3.1.1
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
